name: MCShopSystemPlugin
main: com.n8lm.MCShopSystemPlugin.MainPlugin
version: 0.1.0
commands:
  mcshop:
    description: Get information about this plugin.
    usage: "Usage: '/mcshop' to get information"