name: N8LM MC Shop
main: com.n8lm.MCShopSystemPlugin.MainPlugin
version: 0.1.0
commands:
  n8lmshop:
    description: Get information about this plugin.
    usage: "Usage: '/n8lmshop' to get information"