name: MCShopSystemPlugin
version: 1.1.0
website: mymcshop.com
author: www.n8lm.cn
description: a part of MyMCShop System.

softdepend: [Authme]
main: com.n8lm.MCShopSystemPlugin.MainPlugin

commands:
  mymcshop:
    description: Get information about this plugin.
    usage: "Usage: '/mymcshop' to get information"