name: MCShopSystemPlugin
main: com.n8lm.MCShopSystemPlugin.MainPlugin
version: 1.0.1
website: mymcshop.com
author: www.n8lm.cn
description: a part of MyMCShop System.
commands:
  mymcshop:
    description: Get information about this plugin.
    usage: "Usage: '/mymcshop' to get information"